In [1]:
%matplotlib inline

In [2]:
import matplotlib.pyplot as plt
import math
import numpy as np
import scipy as sp
import sympy as sym
import pandas as pd
import seaborn as sns

In [3]:
otr_table = pd.read_csv('newotrsl.csv', sep=';')

In [4]:
otr_table

№                            industry   1   2   3   4   5  final_product
0  1                      станкостроение  15  12  24  23  16             10
1  2                          энергетика  10   3  35  15   7             30
2  3                      машиностроение  10   5  10  10  10              5
3  4                  автопромышленность  10   5  10   5   5             15
4  5  добыча и переработка углеводородов   7  15  15  10   3             50

In [5]:
industry_sect = otr_table[['№', 'industry']].to_numpy()
industry_sect_pd = pd.DataFrame(industry_sect, columns = ['№ Industry', 'Industry Name'])
industry_sect_pd

№ Industry                       Industry Name
0          1                      станкостроение
1          2                          энергетика
2          3                      машиностроение
3          4                  автопромышленность
4          5  добыча и переработка углеводородов

In [6]:
all_matrix = otr_table.iloc[:,2:7].to_numpy()
all_matrix_pd = pd.DataFrame(all_matrix)
all_table = otr_table.iloc[:,2:].to_numpy()
all_table_pd = pd.DataFrame(all_table)
alltb = np.array(all_table_pd)
gross = [i for i in range ( len(alltb) )]
for i in range ( len(alltb) ):
    gross[i] = alltb[i,:].sum()

In [7]:
gross_table = pd.DataFrame(gross, columns = ['Gross Product',])
gross_table_res = pd.concat([otr_table, gross_table], axis=1)
pd.options.display.float_format = '{:,.3f}'.format
gross_table_res

№                            industry   1   2   3   4   5  final_product  \
0  1                      станкостроение  15  12  24  23  16             10   
1  2                          энергетика  10   3  35  15   7             30   
2  3                      машиностроение  10   5  10  10  10              5   
3  4                  автопромышленность  10   5  10   5   5             15   
4  5  добыча и переработка углеводородов   7  15  15  10   3             50   

   Gross Product  
0            100  
1            100  
2             50  
3             50  
4            100

In [8]:
X_matrix = pd.DataFrame(gross, columns = ['Gross Product',])
X_matrix

Gross Product
0            100
1            100
2             50
3             50
4            100

In [9]:
X_matrix_res = pd.concat([industry_sect_pd,X_matrix],axis=1)
pd.options.display.float_format = '{:,.2f}'.format
X_matrix_res

№ Industry                       Industry Name  Gross Product
0          1                      станкостроение            100
1          2                          энергетика            100
2          3                      машиностроение             50
3          4                  автопромышленность             50
4          5  добыча и переработка углеводородов            100

In [10]:
A_matrix = all_matrix / gross
A_matrix

array([[0.15, 0.12, 0.48, 0.46, 0.16],
       [0.1 , 0.03, 0.7 , 0.3 , 0.07],
       [0.1 , 0.05, 0.2 , 0.2 , 0.1 ],
       [0.1 , 0.05, 0.2 , 0.1 , 0.05],
       [0.07, 0.15, 0.3 , 0.2 , 0.03]])

In [11]:
A_matrix.shape

(5, 5)

In [12]:
Y_matrix = otr_table[['final_product']].to_numpy()
Y_matrix_pd = pd.DataFrame(Y_matrix, columns = ['Final Product'])
Y_matrix_pd_res = pd.concat([industry_sect_pd,Y_matrix_pd], axis=1)
Y_matrix_pd_res.style.hide_index()
pd.options.display.float_format = '{:,.2f}'.format
Y_matrix_pd_res

№ Industry                       Industry Name  Final Product
0          1                      станкостроение             10
1          2                          энергетика             30
2          3                      машиностроение              5
3          4                  автопромышленность             15
4          5  добыча и переработка углеводородов             50

In [13]:
I_matrix = np.identity(5)
I_matrix

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [14]:
I_A_matrix = I_matrix - A_matrix
np.set_printoptions(suppress=True, precision=5)
I_A_matrix

array([[ 0.85, -0.12, -0.48, -0.46, -0.16],
       [-0.1 ,  0.97, -0.7 , -0.3 , -0.07],
       [-0.1 , -0.05,  0.8 , -0.2 , -0.1 ],
       [-0.1 , -0.05, -0.2 ,  0.9 , -0.05],
       [-0.07, -0.15, -0.3 , -0.2 ,  0.97]])

In [15]:
I_A_matrix_inverse = np.linalg.inv(I_A_matrix)
I_A_matrix_inverse

array([[1.73735, 0.50918, 2.1429 , 1.67402, 0.63052],
       [0.59252, 1.35036, 2.04262, 1.31208, 0.4734 ],
       [0.38871, 0.2451 , 2.02303, 0.80367, 0.33179],
       [0.33491, 0.20628, 0.87203, 1.59871, 0.24244],
       [0.40628, 0.3639 , 1.27599, 0.90189, 1.30224]])

In [16]:
allmx = np.array(all_matrix_pd)
Val = [i for i in range ( len(allmx) )]
for i in range ( len(allmx) ):
    Val[i] = gross[i] - allmx[:, i].sum()
new_table = pd.DataFrame(Val, columns = ['Plus Value',])
new_table_res = pd.concat([gross_table_res, new_table], axis=1)
pd.options.display.float_format = '{:,.3f}'.format
new_table_res

№                            industry   1   2   3   4   5  final_product  \
0  1                      станкостроение  15  12  24  23  16             10   
1  2                          энергетика  10   3  35  15   7             30   
2  3                      машиностроение  10   5  10  10  10              5   
3  4                  автопромышленность  10   5  10   5   5             15   
4  5  добыча и переработка углеводородов   7  15  15  10   3             50   

   Gross Product  Plus Value  
0            100          48  
1            100          60  
2             50         -44  
3             50         -13  
4            100          59